config/routes.rb
Rails.application.routes.draw do
  # get "pages/home", to: "pages#home"
  # get "pages/dashboard", to: "pages#dashboard"

  get "/signup", to: "registrations#new", as: :new_registration
  post "/signup", to: "registrations#create", as: :registration
  resource :session, except: %i[new]
  get "/login", to: "sessions#new", as: :new_session
  resources :passwords, param: :token

  resources :counties, only: %i[index show] do
    resources :towns, only: %i[index show]
  end

  get "/towns/:id/food_pantries", to: "towns#food_pantries", as: :town_food_pantries

  # resources :counties do
  #   get "food_pantries", on: :member
  # end


  resources :towns do
    resources :food_pantries
  end

  resources :food_pantries
  resources :counties, only: %i[index show]
  resources :towns, only: %i[index show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "counties#index"
end

app/models/food_pantry.rb
class FoodPantry < ApplicationRecord
  belongs_to :town
  has_many :comments
  accepts_nested_attributes_for :comments
end

app/controllers/food_pantries_controller.rb
class FoodPantriesController < ApplicationController
  before_action :set_food_pantry, only: %i[show edit update destroy]

  # GET /food_pantries or /food_pantries.json
  def index
    @food_pantries = FoodPantry.all
  end

  # GET /food_pantries/1 or /food_pantries/1.json
  def show
    @food_pantry = FoodPantry.includes(:comments, :town).find(params.require(:id))
    @comments = @food_pantry.comments
  end

  # GET /food_pantries/new
  def new
    @food_pantry = FoodPantry.new(town_id: params[:town_id])
    # binding.pry
    # @towns = Town.all
    # @food_pantry.comments.build
  end

  # GET /food_pantries/1/edit
  def edit
  end

  # POST /food_pantries or /food_pantries.json
  def create
    @food_pantry = FoodPantry.new(food_pantry_params)

    respond_to do |format|
      if @food_pantry.save
        format.html { redirect_to @food_pantry, notice: "Food pantry was successfully created." }
        format.json { render :show, status: :created, location: @food_pantry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food_pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_pantries/1 or /food_pantries/1.json
  def update
    respond_to do |format|
      if @food_pantry.update(food_pantry_params)
        format.html { redirect_to @food_pantry, notice: "Food pantry was successfully updated." }
        format.json { render :show, status: :ok, location: @food_pantry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food_pantry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_pantries/1 or /food_pantries/1.json
  def destroy
    @food_pantry.destroy!

    respond_to do |format|
      format.html { redirect_to food_pantries_path, status: :see_other, notice: "Food pantry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food_pantry
    @food_pantry = FoodPantry.find(params.require(:id))
  end

  # Only allow a list of trusted parameters through.
  def food_pantry_params
    params.expect(food_pantry: [ :name, :address_line1, :address_line2, :city, :state, :zip_code, :phone_number, :contact, :verified, :additional_info, :town_id, comments_attributes: [ :id, :comment, :_destroy ] ])
  end
end

app/helpers/food_pantries_helper.rb
module FoodPantriesHelper
  def total_by_county(towns)
    count = 0
    towns.each do |town|
      count += town.food_pantries.count
    end
    count
  end
end

app/views/food_pantries/_food_pantry.html.erb
<div id="<%= dom_id food_pantry %>">
  <p>
    <strong>Name:</strong>
    <%= food_pantry.name %>
  </p>

  <p>
    <strong>Address line1:</strong>
    <%= food_pantry.address_line1 %>
  </p>

  <p>
    <strong>Address line2:</strong>
    <%= food_pantry.address_line2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= food_pantry.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= food_pantry.state %>
  </p>

  <p>
    <strong>Zip code:</strong>
    <%= food_pantry.zip_code %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= food_pantry.phone_number %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= food_pantry.contact %>
  </p>

  <p>
    <strong>Verified:</strong>
    <%= food_pantry.verified %>
  </p>

  <p>
    <strong>Comments:</strong>
    <% food_pantry.comments.each do |comment| %>
      <p> <%= comment.user.user_name %></p>
      <p><%= comment.created_at %></p>
      <p><%= comment.body %></p>
    <% end %>
  </p>

  <p>
    <strong>Town:</strong>
    <%= food_pantry.town.name %>
  </p>

</div>

app/views/food_pantries/_form.html.erb
  <div class="space-y-12">
    <div class="border-b border-gray-900/10 pb-12">
      <h2 class="text-base/7 font-semibold text-gray-900">Profile</h2>
      <p class="mt-1 text-sm/6 text-gray-600">This information will be displayed publicly so be careful what you share.</p>      
      
      
      <%= form_with(model: food_pantry) do |form| %>
        <% if food_pantry.errors.any? %>    
          <div style="color: red">
            <h2><%= pluralize(food_pantry.errors.count, "error") %> prohibited this food_pantry from being saved:</h2>

            <ul>
              <% food_pantry.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name %>
        </div>

        <div>
          <%= form.label :address_line1, style: "display: block" %>
          <%= form.text_field :address_line1 %>
        </div>

        <div>
          <%= form.label :address_line2, style: "display: block" %>
          <%= form.text_field :address_line2 %>
        </div>

       <% if form.object.town_id? %>
         <div>
           <%= form.label :town_name, "City/Town:", style: "display: block" %>
           <%= form.text_field :town_name, value: food_pantry.town&.name, readonly: true %>
           <%= form.hidden_field :town_id %>
         </div>
        <% else %>
          <%= form.collection_select(:town, :town_id, Town.all, :id, :name) %>
        <% end %>

        <div>
          <%= form.label :state, style: "display: block" %>
          <%= form.text_field :state %>
        </div>

        <div>
          <%= form.label :zip_code, style: "display: block" %>
          <%= form.text_field :zip_code %>
        </div>

        <div>
          <%= form.label :phone_number, style: "display: block" %>
          <%= form.text_field :phone_number %>
        </div>

        <div>
          <%= form.label :contact, style: "display: block" %>
          <%= form.text_field :contact %>
        </div>

        <div>
          <%= form.label :verified, style: "display: block" %>
          <%= form.checkbox :verified %>
        </div>

        <div>
          <%= form.label :comments, style: "display: block" %>
          <%= form.fields_for :comments do |comment_form| %>
            <%= comment_form.label :body %>
            <%= comment_form.text_area :body %>
          <% end %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      <% end %>
  </div>
</div>

app/views/food_pantries/edit.html.erb
<% content_for :title, "Editing food pantry" %>

<h1>Editing food pantry</h1>

<%= render "form", food_pantry: @food_pantry %>

<br>

<div>
  <%= link_to "Show this food pantry", @food_pantry %> |
  <%= link_to "Back to food pantries", food_pantries_path %>
</div>

app/views/food_pantries/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Food pantries" %>

<h1>Food pantries</h1>

<div id="food_pantries">
  <% @food_pantries.each do |food_pantry| %>
    <%= render food_pantry %>
    <p>
      <%= link_to "Show this food pantry", food_pantry %>
    </p>
  <% end %>
</div>

<%= link_to "New food pantry", new_food_pantry_path %>

app/views/food_pantries/new.html.erb
<% content_for :title, "New food pantry" %>

<h1>New food pantry</h1>

<%= render "form", food_pantry: @food_pantry %>

<br>

<div>
  <%= link_to "Back to food pantries", food_pantries_path %>
</div>

app/views/food_pantries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food_pantry %>

<div>
  <%= link_to "Edit this food pantry", edit_food_pantry_path(@food_pantry) %> |
  <%= link_to "Back to food pantries", food_pantries_path %>

  <%= button_to "Destroy this food pantry", @food_pantry, method: :delete %>
</div>

<%= turbo_frame_tag "comments" do %>
  <%= render @food_pantry.comments %>
<% end %>