config/routes.rb
Rails.application.routes.draw do
  # get "pages/home", to: "pages#home"
  # get "pages/dashboard", to: "pages#dashboard"

  get "/signup", to: "registrations#new", as: :new_registration
  post "/signup", to: "registrations#create", as: :registration
  resource :session, except: %i[new]
  get "/login", to: "sessions#new", as: :new_session
  resources :passwords, param: :token

  resources :counties, only: %i[index show] do
    resources :towns, only: %i[index show]
  end

  get "/towns/:id/food_pantries", to: "towns#food_pantries", as: :town_food_pantries

  # resources :counties do
  #   get "food_pantries", on: :member
  # end


  resources :towns do
    resources :food_pantries
  end

  resources :food_pantries
  resources :counties, only: %i[index show]
  resources :towns, only: %i[index show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "counties#index"
end

app/models/county.rb
class County < ApplicationRecord
  has_many :towns
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  include FoodPantryCounter
  before_action :set_county, only: %i[show]
  def index
    @counties = County.all
  end

  def show
    @towns = @county.towns
    # @towns_hash = towns_hash(@towns)
    # @total_by_county = total_by_county(@towns)
  end


  def food_pantries
    @county = County.find(params[:id])
    @food_pantries = @county.towns.includes(:food_pantries)

    respond_to do |format|
      format.turbo_stream
      # format.html { render :food_pantries }
    end
  end

  private

  def set_county
    @county = County.find(params.require(:id))
  end
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/food_pantries.html.erb
<div>
  <h1 class="font-bold text-4xl">Counties#food_pantries</h1>
  <p>Find me in app/views/counties/food_pantries.html.erb</p>
</div>

app/views/counties/food_pantries.turbo_stream.erb
<turbo-frame id="food_pantries">
  <h1>Food Pantries in <%= @county.name%></h1>
  <h3>Total Food Pantries: <%= @county.towns.sum { |town| town.food_pantries.count } %></h3>
  <% @county.towns.each do |town| %>
    <details>
      <summary><%= town.name %> (Food Pantries: <%= town.food_pantries.count %>)</summary>
      <ul>
        <% town.food_pantries.each do |pantry| %>
          <li><%= link_to pantry.name, town_food_pantries_path town %></li>
        <% end %>
      </ul>
    </details>
  <% end %>
</turbo-frame>

app/views/counties/index.html.erb
<div class="text-3xl px-6 py-4">Counties List</div>
<div>
  <ul>
    <% @counties.each do |county| %>
      <li class="px-6 py-4">
        <%= link_to county.name, county%>
      </li>
    <% end %>
  </ul>
</div>

app/views/counties/show.html.erb
<div class="text-3xl px-6 py-4">
  <%= "Cities & Towns In #{@county.name}"%>
</div>
<div class="text-xl px-6 py-4">
  <%= "Total Food Pantry Count For #{@county.name} county: #{total_by_county(@county.towns)}"%>
</div >
<div>
  <ul>
    <% @towns.each do |town| %>
      <li class="px-6 py-4">
        <div><%= link_to "#{town.name} (#{town.food_pantries.count})", town_food_pantries_path(town.id) %></div>
        <div class="text-blue"><%= link_to "Add New Food Pantry", new_food_pantry_path(town_id: town.id) %></div>
      </li>
    <% end %>
  </ul>
</div>