config/routes.rb
Rails.application.routes.draw do
  # get "pages/home", to: "pages#home"
  # get "pages/dashboard", to: "pages#dashboard"

  get "/signup", to: "registrations#new", as: :new_registration
  post "/signup", to: "registrations#create", as: :registration
  resource :session, except: %i[new]
  get "/login", to: "sessions#new", as: :new_session
  resources :passwords, param: :token

  resources :counties, only: %i[index show] do
    resources :towns, only: %i[index show]
  end

  get "/towns/:id/food_pantries", to: "towns#food_pantries", as: :town_food_pantries

  # resources :counties do
  #   get "food_pantries", on: :member
  # end


  resources :towns do
    resources :food_pantries
  end

  resources :food_pantries
  resources :counties, only: %i[index show]
  resources :towns, only: %i[index show]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "counties#index"
end

app/models/town.rb
class Town < ApplicationRecord
  belongs_to :county
  has_many :food_pantries
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_towns, only: %i[show]
  def index
    @towns = Town.all
  end

  def show
  end

  def food_pantries
    @town = Town.includes(:food_pantries).find(params[:id])
    @food_pantries = @town.food_pantries

    respond_to do |format|
      format.turbo_stream
      format.html { render :food_pantries }
    end
  end

  private

  def set_towns
    @town = Town.find(params.require(:id))
  end
end

app/helpers/towns_helper.rb
module TownsHelper
  def load_towns
    Town.all
  end
end

app/views/towns/food_pantries.html.erb
<div class="text-1xl px-6 py-4">
  <%= "Food Pantries in #{@town.name} #{@town.food_pantries.count}" %>
</div>
<ul>
  <% @food_pantries.each do |pantry| %>
    <li class="px-6 py-4"><%= link_to pantry.name, food_pantry_path(pantry.id) %></li>
  <% end %>
</ul>

app/views/towns/food_pantries.turbo_stream.erb
<turbo-frame id="food_pantries">
  <h1>Food Pantries in <%= @town.name%></h1>
    <details>
      <summary><%= @town.name %> (Food Pantries: <%= @town.food_pantries.count %>)</summary>
      <ul>
        <% @food_pantries.each do |pantry| %>
          <li><%= link_to pantry.name, food_pantry_path pantry %></li>
        <% end %>
      </ul>
    </details>
  <% end %>
</turbo-frame>

app/views/towns/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Towns#index</h1>
  <p>Find me in app/views/towns/index.html.erb</p>
</div>

app/views/towns/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Towns#show</h1>
  <p>Find me in app/views/towns/show.html.erb</p>
</div>